services:
  # Service untuk Database PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: warehaus-db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_rahasia
      POSTGRES_DB: WareHausDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Service untuk Aplikasi .NET 10 kamu
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehaus-api
    ports:
      - "5000:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
    depends_on:
      - db

volumes:
  pgdata: