// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WareHaus.Api.Data;

#nullable disable

namespace WareHaus.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505141643_InitialPostgreSqlCreate")]
    partial class InitialPostgreSqlCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WareHaus.Api.Models.POItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("PurchaseOrdersId")
                        .HasColumnType("integer");

                    b.Property<int>("QtyExpected")
                        .HasColumnType("integer");

                    b.Property<int>("QtyReceived")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductsId");

                    b.HasIndex("PurchaseOrdersId");

                    b.ToTable("POItems");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PackingItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PackingTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("QtyVerified")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PackingTaskId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductsId");

                    b.ToTable("PackingItems");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PackingTasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SOId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPackage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SOId");

                    b.ToTable("PackingTasks");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PurchaseOrders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("WareHaus.Api.Models.ReceivingLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("POItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("POItemsId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("PurchaseOrdersId")
                        .HasColumnType("integer");

                    b.Property<int>("QtyReceived")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("POItemsId");

                    b.HasIndex("ProductsId");

                    b.HasIndex("PurchaseOrdersId");

                    b.ToTable("ReceivingLogs");
                });

            modelBuilder.Entity("WareHaus.Api.Models.SOItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("QtyOrdered")
                        .HasColumnType("integer");

                    b.Property<int>("QtyPicked")
                        .HasColumnType("integer");

                    b.Property<int>("SOId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductsId");

                    b.HasIndex("SOId");

                    b.ToTable("SOItems");
                });

            modelBuilder.Entity("WareHaus.Api.Models.SalesOrders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SONumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SONumber")
                        .IsUnique();

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Shelves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aisle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVolume")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QRCodePath")
                        .HasColumnType("text");

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.Property<int?>("ZonesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZonesId");

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Shipments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ManifestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PackingTaskId")
                        .HasColumnType("integer");

                    b.Property<string>("ShippingLabelUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PackingTaskId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Stocks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShelfId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShelvesId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductsId");

                    b.HasIndex("ShelvesId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Zones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LevelPerShelf")
                        .HasColumnType("integer");

                    b.Property<int>("ShelfPerAisle")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAisle")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("WareHaus.Api.Models.POItems", b =>
                {
                    b.HasOne("WareHaus.Api.Models.Products", "Products")
                        .WithMany("POItems")
                        .HasForeignKey("ProductsId");

                    b.HasOne("WareHaus.Api.Models.PurchaseOrders", "PurchaseOrders")
                        .WithMany("POItems")
                        .HasForeignKey("PurchaseOrdersId");

                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PackingItems", b =>
                {
                    b.HasOne("WareHaus.Api.Models.PackingTasks", "PackingTasks")
                        .WithMany("PackingItems")
                        .HasForeignKey("PackingTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WareHaus.Api.Models.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WareHaus.Api.Models.Products", null)
                        .WithMany("PackingItems")
                        .HasForeignKey("ProductsId");

                    b.Navigation("PackingTasks");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PackingTasks", b =>
                {
                    b.HasOne("WareHaus.Api.Models.SalesOrders", "SalesOrders")
                        .WithMany("PackingTasks")
                        .HasForeignKey("SOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("WareHaus.Api.Models.ReceivingLogs", b =>
                {
                    b.HasOne("WareHaus.Api.Models.POItems", "POItems")
                        .WithMany("ReceivingLogs")
                        .HasForeignKey("POItemsId");

                    b.HasOne("WareHaus.Api.Models.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsId");

                    b.HasOne("WareHaus.Api.Models.PurchaseOrders", "PurchaseOrders")
                        .WithMany("ReceivingLogs")
                        .HasForeignKey("PurchaseOrdersId");

                    b.Navigation("POItems");

                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("WareHaus.Api.Models.SOItems", b =>
                {
                    b.HasOne("WareHaus.Api.Models.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WareHaus.Api.Models.Products", null)
                        .WithMany("SOItems")
                        .HasForeignKey("ProductsId");

                    b.HasOne("WareHaus.Api.Models.SalesOrders", "SalesOrders")
                        .WithMany("SOItems")
                        .HasForeignKey("SOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Shelves", b =>
                {
                    b.HasOne("WareHaus.Api.Models.Zones", "Zones")
                        .WithMany("Shelves")
                        .HasForeignKey("ZonesId");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Shipments", b =>
                {
                    b.HasOne("WareHaus.Api.Models.PackingTasks", "PackingTasks")
                        .WithMany("Shipments")
                        .HasForeignKey("PackingTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PackingTasks");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Stocks", b =>
                {
                    b.HasOne("WareHaus.Api.Models.Products", "Products")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductsId");

                    b.HasOne("WareHaus.Api.Models.Shelves", "Shelves")
                        .WithMany("Stocks")
                        .HasForeignKey("ShelvesId");

                    b.Navigation("Products");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("WareHaus.Api.Models.POItems", b =>
                {
                    b.Navigation("ReceivingLogs");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PackingTasks", b =>
                {
                    b.Navigation("PackingItems");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Products", b =>
                {
                    b.Navigation("POItems");

                    b.Navigation("PackingItems");

                    b.Navigation("SOItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PurchaseOrders", b =>
                {
                    b.Navigation("POItems");

                    b.Navigation("ReceivingLogs");
                });

            modelBuilder.Entity("WareHaus.Api.Models.SalesOrders", b =>
                {
                    b.Navigation("PackingTasks");

                    b.Navigation("SOItems");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Shelves", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Zones", b =>
                {
                    b.Navigation("Shelves");
                });
#pragma warning restore 612, 618
        }
    }
}
