// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WareHaus.API.Data;

#nullable disable

namespace WareHaus.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429022410_RefactorPurchaseOrderSetup")]
    partial class RefactorPurchaseOrderSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WareHaus.Api.Models.POItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("POId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PurchaseOrdersId")
                        .HasColumnType("char(36)");

                    b.Property<int>("QtyExpected")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductsId");

                    b.HasIndex("PurchaseOrdersId");

                    b.ToTable("POItems");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PurchaseOrders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("WareHaus.Api.Models.ReceivingLogs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("POItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("POItemsId")
                        .HasColumnType("char(36)");

                    b.Property<int>("QtyReceived")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("POItemsId");

                    b.ToTable("ReceivingLogs");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Shelves", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Aisle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentVolume")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ZonesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ZonesId");

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Stocks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductsId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ShelfId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ShelvesId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductsId");

                    b.HasIndex("ShelvesId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Zones", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LevelPerShelf")
                        .HasColumnType("int");

                    b.Property<int>("ShelfPerAisle")
                        .HasColumnType("int");

                    b.Property<int>("TotalAisle")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("WareHaus.Api.Models.POItems", b =>
                {
                    b.HasOne("WareHaus.Api.Models.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsId");

                    b.HasOne("WareHaus.Api.Models.PurchaseOrders", "PurchaseOrders")
                        .WithMany("POItems")
                        .HasForeignKey("PurchaseOrdersId");

                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("WareHaus.Api.Models.ReceivingLogs", b =>
                {
                    b.HasOne("WareHaus.Api.Models.POItems", "POItems")
                        .WithMany("ReceivingLogs")
                        .HasForeignKey("POItemsId");

                    b.Navigation("POItems");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Shelves", b =>
                {
                    b.HasOne("WareHaus.Api.Models.Zones", "Zones")
                        .WithMany("Shelves")
                        .HasForeignKey("ZonesId");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Stocks", b =>
                {
                    b.HasOne("WareHaus.Api.Models.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsId");

                    b.HasOne("WareHaus.Api.Models.Shelves", "Shelves")
                        .WithMany("Stocks")
                        .HasForeignKey("ShelvesId");

                    b.Navigation("Products");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("WareHaus.Api.Models.POItems", b =>
                {
                    b.Navigation("ReceivingLogs");
                });

            modelBuilder.Entity("WareHaus.Api.Models.PurchaseOrders", b =>
                {
                    b.Navigation("POItems");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Shelves", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("WareHaus.Api.Models.Zones", b =>
                {
                    b.Navigation("Shelves");
                });
#pragma warning restore 612, 618
        }
    }
}
